@startuml level4
!include <C4/C4_Container>

package REST_API <<Rectangle>> {

    package Controllers {
        class tracksController {
            +getCancion()
            +getLetra()
            +getAllCanciones()
            +postCancion()
            +buscarCancion()
            +deleteCancion()
            +updateCancion()
        }

        class tracksRoutes {
            #get()
            #put()
            #post()
            #delete()
        }
    }

    package Database {
        class database {
            +obtenerConexion()
        }
    }

    tracksRoutes "1" *-- "1" tracksController : se compone
    tracksController "1" --> "1" database : utiliza

}


@enduml